Websteros/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from wikibsteros import views
from django.conf.urls.i18n import i18n_patterns
from django.utils import translation
from django.utils.translation import ugettext as _

app_name = 'Websteros'

urlpatterns = []
urlpatterns += i18n_patterns(
    path('', views.index, name='index'),
    path('', include('wikibsteros.urls', namespace='wikibsteros')),
    path('account/', include('account.urls', namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^admin/', admin.site.urls)
    ] + urlpatterns

account/urls.py
""" account app urls """
from django.urls import path
from . import views # import views so we can use them in urls.

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
]

wikibsteros/urls.py
# -*- coding: utf-8 -*-
""" wikibsteros app urls """
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'wikibsteros'

urlpatterns = [
    path('', views.index, name='index'),
    path('wikibsteros', views.wikibsteros, name='wikibsteros'),
    path('universe', views.universe, name='universe'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('log_out', views.log_out, name='logout'),
    path('universe/battle', views.battle, name='battle'),
    path('universe/test', views.test_i18n, name='test'),
    path('universe/weather', views.weather, name='weather'),
    path('wikibsteros/character/<str:id>', views.character, name='character'),
    path('wikibsteros/house/<str:id>', views.house, name='house'),
    path('wikibsteros/city/<str:id>', views.city, name='city'),
    path('wikibsteros/articles/', views.articles, name='articles'),
    path('wikibsteros/article/<str:id>', views.article, name='article'),
    path('universe/battle_result', views.battle_result, name='battle_result'),
    path('universe/maggy', views.maggy, name='maggy'),
    path('wikibsteros/search', views.wikibsteros_search, name='wikibsteros_search'),
    path('wikibsteros/add_comment_city/<str:city_id>', views.add_a_comment_city, name='add_a_comment_city'),
    path('wikibsteros/add_comment_character/<str:character_id>', views.add_a_comment_character, name='add_a_comment_character'),
    path('wikibsteros/add_comment_article/<str:article_id>', views.add_a_comment_article, name='add_a_comment_article'),
    path('wikibsteros/add_a_vote/<str:char_id>', views.add_a_vote_character, name='add_a_vote'),
]

wikibsteros/forms.py
"""forms which manage the accounts"""
from django import forms
from langdetect import detect
from django.utils import translation
from django.utils.translation import ugettext_lazy as _
from .other_functions import choose_a_region, choose_a_house, choose_a_character
from captcha.widgets import ReCaptchaV2Invisible, widgets

class LoginForm(forms.Form):
    """the form to login"""
    user = forms.CharField(max_length=100, widget=forms.TextInput(attrs=\
    {'placeholder': (_('Username')), 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))
    mdp = forms.CharField(widget=forms.PasswordInput(attrs=\
    {'placeholder': (_('Password')), 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))

class RegisterForm(forms.Form):
    """the form to create an account"""
    user_name = forms.CharField(required=True, max_length=100, widget=forms.TextInput(attrs=\
    {'placeholder': (_('Username')), 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs=\
    {'placeholder': 'E-mail', 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs=\
    {'placeholder': (_('Password')), 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))
    checkbox = forms.BooleanField(required=True, widget=forms.CheckboxInput(attrs=\
    {'style':'font-size:450%;'}))
    HOUSE_CHOICES = choose_a_house()
    field_1 = forms.ChoiceField(choices=HOUSE_CHOICES, label="",
                                required=True,
                                widget=forms.Select(attrs=\
                                {'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0 w-100'}))

    REGION_CHOICES = choose_a_region()
    field_2 = forms.ChoiceField(choices=REGION_CHOICES, label="",
                                required=True, widget=forms.Select(attrs=\
                                {'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0 w-100'}))

class ContactForm(forms.Form):
    """contact form"""
    from_email = forms.EmailField(widget=forms.EmailInput(attrs=\
    {'placeholder': (_('Your e-mail')),
     'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}),
                                  required=True)
    subject = forms.CharField(max_length=10**3, widget=forms.TextInput(attrs=\
    {'placeholder': (_('Subject')), 'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))
    message = forms.CharField(max_length=10**10, widget=forms.Textarea(attrs=\
    {'placeholder': (_('Your message')),
     'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0'}))

class ChatRoomForm(forms.Form):
    """chat room textarea"""
    chat = forms.CharField(max_length=10**10, widget=forms.Textarea(attrs=\
        {'placeholder': (_('Type your message')),
         'class': 'input-group-text d-flex bg-light rounded-0 w-100 text-lg-left'}))

class ClairvoyanceForm(forms.Form):
    """ Maggy form """
    GENDER_CHOICES = ((0, _('👨 CHOOSE A GENDER 👩')), ('Male', _('Male')), ('Female', _('Female')))
    
    field_1 = forms.ChoiceField(choices=GENDER_CHOICES, label="",
                                required=True,
                                widget=forms.Select(attrs=\
                                {'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0 w-100', \
                                'style' : 'text-align-last: center;'}))
    LIST_OF_CHARACTERS = choose_a_character()
    character = forms.ChoiceField(choices=LIST_OF_CHARACTERS, label="",
                                  required=True,
                                  widget=forms.Select(attrs=\
                                  {'class': 'form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0 w-100', \
                                   'style' : 'text-align-last: center;'}))

wikibsteros/views.py
"""views of the app wikibsteros"""
import os
import random
import calendar
import datetime
import json
import pytz
import urllib
import online_users.models
from django.conf import settings
from .other_functions import situation_in_the_crowns, choose_a_region, \
battle_init, battle_cards, get_cards, fight, random_quote_maggy
from .database import InsertObjects, Article, WeatherObjects
from .constants import SECOND_ARTICLE_RESUME_EN
from django.http import HttpResponse
from .forms import LoginForm, RegisterForm, ContactForm, ChatRoomForm, ClairvoyanceForm
from .models import Character, Houses, Chat, City, PostACommentCity, UserChoices, \
PostACommentCharacter, UserChoices, PostACommentArticle, VotesCharacters
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.template import loader
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.utils.translation import ungettext
from django.utils.translation import pgettext
from django.utils import translation
from django.core.mail import send_mail, BadHeaderError
from django.utils.translation import ugettext_lazy as __
from django.template.defaulttags import register
from django.template.defaultfilters import register
from django.http import JsonResponse, HttpResponseRedirect
from django import template

@register.filter
def index(List, i):
    return List[int(i)]

@register.filter
def return_item(l, i):
    try:
        return l[i]
    except:
        return None

def set_language(request):
    next = request.REQUEST.get('next', None)
    if not next:
        next = request.META.get('HTTP_REFERER', None)
    if not next:
        next = '/'
    response = http.HttpResponseRedirect(next)
    if request.method == 'GET':
        lang_code = request.GET.get('language', None)
        if lang_code and check_for_language(lang_code):
            if hasattr(request, 'session'):
                request.session['django_language'] = lang_code
            else:
                response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code)
            translation.activate(lang_code)
    return response


def get_hours(loc, zone):
    """ cities hours """
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', \
    'September', 'October', 'November', 'December']
    got_loc = datetime.datetime.now(pytz.timezone(zone)) # you could pass `timezone` object here
    my_date = got_loc.today()
    fmt = '%I %M %S %p'
    result = loc, calendar.day_name[my_date.weekday()] + ',', got_loc.day, \
    months[got_loc.month - 1], str(got_loc.year), got_loc.strftime(fmt)
    return result

def set_hours():
    pyk = get_hours(_('Pyk, Casterly Rock, Oldtown'), 'Brazil/DeNoronha')
    sunspear = get_hours(_('Sunspear, Dragonstone, Storm‘s End'), 'Europe/Madrid')
    highgarden = get_hours(_('Highgarden, Riverrun, The Twins, Winterfell'), 'Etc/GMT+1')
    kings_landings = get_hours(_('King‘s Landings, The Eyrie, Castleblack'), 'Etc/GMT-1')
    tyrosh = get_hours('Tyrosh', 'Europe/Bucharest')
    hours_lefts = [pyk, highgarden, kings_landings, sunspear, tyrosh]
    pentos = get_hours('Pentos, Myr, Braavos, Lys', 'Europe/Bucharest')
    lorath = get_hours('Lorath, Norvos', 'Europe/Samara')
    volantis = get_hours('Volantis', 'Asia/Omsk')
    yunkai = get_hours('Yunkaï, Meeren, Astapor', 'Asia/Tokyo')
    qarth = get_hours('Qarth', 'Pacific/Fiji')
    hours_right = [pentos, lorath, volantis, yunkai, qarth]
    return hours_lefts, hours_right

def get_online_users():
    """display all online users"""
    user_activity_objects = online_users.models.OnlineUserActivity.get_user_activities\
    (datetime.timedelta(minutes=1))
    number_of_active_users = user_activity_objects.count()
    list_of_onlines = []
    for act in user_activity_objects:
        list_of_onlines.append(User.objects.get(pk=act.user_id))
    print(list_of_onlines)
    template = loader.get_template('footer.html')
    return list_of_onlines, number_of_active_users

def get_the_name_from_the_user_id(this_id):
    char = User.objects.filter(id=this_id)
    for this_char in char:
        return this_char.username

@register.simple_tag
def get_the_id_from_the_character(this_name):
    char = Character.objects.filter(name=this_name)
    for this_char in char:
        return this_char.id

@register.simple_tag
def get_the_id_from_the_house(this_name):
    house = Houses.objects.filter(name=this_name)
    for this_house in house:
        return this_house.id

def get_the_picture_from_the_char_id(id):
    char = Character.objects.filter(id=id)
    for this_char in char:
        return this_char.image

@register.simple_tag
def get_the_location_from_the_char_id(id):
    char = Character.objects.filter(id=str(id))
    for this_char in char:
        return _(this_char.location)

@register.simple_tag
def get_the_id_from_the_city_name(name):
    city = City.objects.filter(name=name)
    for this_city in city:
        return str(this_city.id)

@register.simple_tag
def loc_pandas_char(the_list, a_a, b_b):
    return the_list.loc[a_a, b_b]

@register.simple_tag
def random_item_in_list(the_list):
    return random.choice(the_list)

def get_current_lang():
    """ get the langage of the web page : fr or en or cl"""
    return translation.get_language()

@register.simple_tag
def translate(text):
    try:    
        return _(text)
    except:
        print("exception")

def index(request):
    """index page"""
    # cities hours recovery
    hours_lefts, hours_right = set_hours()
    # call the function crown situation
    days_passed, names_sovereings, names_houses, names_regions, names_images, \
    names_landscapes = situation_in_the_crowns()
    # insert objects in database
    InsertObjects.insert_houses()
    InsertObjects.insert_articles()
    InsertObjects.insert_users()
    InsertObjects.insert_cities()
    InsertObjects.insert_characters()
    InsertObjects.update_char_from_database()
    InsertObjects.update_city_from_database()
    
    #InsertObjects.get_id_char()
    three_recent_articles = Article.objects.order_by('-date')[:3]
    articles = Article.objects.all()
    choose_a_region()
    #dict_users()
    # Get the number of online people django (last activity max = one minute)
    list_of_onlines, number_of_active_users = get_online_users()

    if request.method == 'POST':
        # A form bound to the POST data
        form_1 = LoginForm(request.POST)
        form_2 = RegisterForm(request.POST)
        form_3 = ContactForm(request.POST)
        form_4 = ChatRoomForm(request.POST)
        # All validation rules pass
        if form_1.is_valid():
            # Process the data in form.cleaned_data
            user = form_1.cleaned_data['user']
            mdp = form_1.cleaned_data['mdp']
            user = authenticate(username=user, password=mdp)
            login(request, user)
            messages.success(request, 'Vous avez été connecté.')
            request.session.set_expiry(900)
            return redirect('index')
        if form_2.is_valid():
            mail = request.POST.get('email')
            user_name = request.POST.get('user_name')
            password = request.POST.get('password')
            allegiance = request.POST.get('field_1')
            region = request.POST.get('field_2')
            email = form_2.cleaned_data['email']
            username = form_2.cleaned_data['user_name']
            raw_password = form_2.cleaned_data['password']
            recaptcha_response = request.POST.get('g-recaptcha-response')
            #---- captcha -----#
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if recaptcha_response:
                try:
                    User.objects.create_user(username, mail, raw_password)
                    UserChoices.objects.create(chosen_allegiance=allegiance, \
                    chosen_region=region, user_id=User.objects.all().count()+2)
                    messages.success(request, _("Your account has been successfully created. You can now log in."))
                    return redirect('index')
                except:
                    messages.error(request, _("Oops. It seems that something gets wrongs."))
                    return redirect('index')
            else:
                messages.error(request, _("It seems that the captcha has not been validated."))
                return redirect('index')
        if form_3.is_valid():
            subject = form_3.cleaned_data['subject']
            from_email = form_3.cleaned_data['from_email']
            message = form_3.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['websteros@yahoo.com'])
                messages.success(request, _('Your email has been sent.'))
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('index')
        if form_4.is_valid():
            chat = form_4.cleaned_data['chat']
            current_user = request.user
            user = User.objects.get(id=current_user.id)
            print(chat)
            #staffprofile.user = user
            Chat.objects.create(message=chat, user_id=user.id)
            #return JsonResponse({'msg': chat})

    else:
        form_1 = LoginForm() # An unbound form
        form_2 = RegisterForm()
        form_3 = ContactForm()
        form_4 = ChatRoomForm()

wikibsteros/templates/city.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}
{% load humanize %}
{% include 'head.html' %}
{% include 'little-nav.html' %}
<section class="bg-light">
    <div style="padding-top:50px"></div>
    <div class="container">
        <div class="row">
            <div class="col-8">
                <h2>{% trans this_city.name %}</h2>
                <hr />
                <h5>{% trans "History" context "Story" %} </h5>
                <hr />
                <h5>{% trans "Geography" %} </h5>
                <hr />
                <h5>{% trans "Population" %} </h5>
                <hr />
                <h5><a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                    aria-controls="collapseExample">{% trans "Comments" %}({{ number_of_comments }})</a></h5>
                <div class="collapse" id="collapseExample">
                    {% for c in comments %}
                    <div class="card card-body"> 
                            <b>{{ c.message }}</b>
                            <br/>
                            <small>
                            {% trans "By" %} <em>{% return_char c.user_id %}</em>
                            <br/>
                            {{ c.created }}</small>
                    </div>
                    <br/>
                    {% endfor %}
                </div>
       
            </div>
            <div class="col-4">
                <ul class="list-group text-center bg-danger rounded" style="list-style-type: none">
                    {% if not this_city.image %}
                    
                    {% else %}
                    <li><img src="{% static 'wikibsteros/img/' %}{{ this_city.image }}" style="width: 100%"
                            class="rounded"></li>
                    {% endif %}
                    <div style="padding-bottom: 1em"></div>
                    <li>{% trans "Name : " %}{% trans this_city.name %}</li>
                    <div style="padding-bottom: 1em"></div>
                    <li>{% trans "Type : " %}{% trans this_city.type %}</li>
                    <div style="padding-bottom: 1em"></div>
                    <li>{% trans "Location : " %}{% trans this_city.location %}</li>
                    <div style="padding-bottom: 1em"></div>
                    {% if this_city.population == 0 %}
                    <li>{% trans "Population : " %} Unknown </li>
                    {% elif this_city.name == "King‘s Landing" %}
                    <li>{% trans "Population : " %} ~ 500 000 {% trans "inhabitants" %} {% trans "(before The battle of King's Landing)" %}</li>
                    ~ {{ this_city.population|intcomma }} {% trans "inhabitants" %} {% trans "(at present)" %}
                    <br/>{% trans "(Ranked " %} : {{ rank }}<sup>{% trans exponent %}</sup>)</li>
                    {% else %}
                    <li>{% trans "Population : " %} ~ {{ this_city.population|intcomma }} {% trans "inhabitants" %} 
                    <br/>{% trans "(Ranked " %} : {{ rank }}<sup>{% trans exponent %}</sup>)</li>
                    {% endif %}
                    <div style="padding-bottom: 1em"></div>
                </ul>
            </div>
            <div class="container">
                <div style="padding-bottom: 4em"></div>
                <div class="row text-center">
                    <div class="col">
                        <p><a href="{% url 'wikibsteros:city' random_city %}">{% trans "Get a random city" %}</a></p>
                    </div>
                    <div class="col">
                        {% if previous.name %}
                        <p><a href="{% url 'wikibsteros:city' this_city.id|add:'-1' %}">← {{ previous.name }} </a></p>
                        {% endif %}
                    </div>
                    <div class="col">
                        {% if next.name %}
                        <p><a href="{% url 'wikibsteros:city' this_city.id|add:'1' %}">{{ next.name }} →</a></p>
                        {% endif %}
                    </div>
                </div>
                <div style="padding-bottom: 1em"></div>
            </div>
           
            <div class="container w-50">
                <!-- CHANGE THE URL HERE -->
                <form action="{% url 'wikibsteros:add_a_comment_city' this_city.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea name="message" class="form-control" id="message" rows="5"
                            placeholder="{% trans 'Post a comment' %}" required></textarea>
                    </div>
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary float-right">{% trans "Submit" %}</button>
                    {% else %}
                    <div class="alert alert-danger te" role="alert">
                        {% trans "You must be logged in to post a comment" %}
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
        <div style="padding-bottom: 2em"></div>
</section>
{% include 'footer.html' %}

wikibsteros/templates/little-nav.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
        aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand text-white" href="{% url 'wikibsteros:index' %}">{% trans "Home" %}</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'wikibsteros:universe' %}">{% trans "Universe" %}<span class="sr-only">(current)</span></a>
            </li>
            
        </ul>
        <a class="nav-link dropdown-toggle" href="" id="dropdown09" data-toggle="dropdown" aria-haspopup="true"
      aria-expanded="false"><span class="flag-icon flag-icon-us"> </span> {% trans "English" %}</a>
        
      <div class="dropdown-menu" aria-labelledby="dropdown09">
        {% if the_path|length == 1 %}
        <a class="dropdown-item" href="/en/{% for c in the_path %}{{ c }}{% endfor %}"><span class="flag-icon flag-icon-us"></span> {% trans "English" %}</a>
        {% else %}
        <a class="dropdown-item" href="/en/{% for c in the_path %}{{ c }}/{% endfor %}"><span class="flag-icon flag-icon-us"></span> {% trans "English" %}</a>
        {% endif %}
        {% if the_path|length == 1 %}
        <a class="dropdown-item" href="/fr/{% for c in the_path %}{{ c }}{% endfor %}"><span class="flag-icon flag-icon-fr"></span> {% trans "French" %}</a>
        {% else %}
        <a class="dropdown-item" href="/fr/{% for c in the_path %}{{ c }}/{% endfor %}"><span class="flag-icon flag-icon-fr"></span> {% trans "French" %}</a>
        {% endif %}
        {% if the_path|length == 1 %}
        <a class="dropdown-item" href="/cl/{% for c in the_path %}{{ c }}{% endfor %}"><span class="flag-icon flag-icon-cl"></span> {% trans "Spanish" %}</a>
        {% else %}
        <a class="dropdown-item" href="/cl/{% for c in the_path %}{{ c }}/{% endfor %}"><span class="flag-icon flag-icon-cl"></span> {% trans "Spanish" %}</a>
        {% endif %}
    </div>
    
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="{% trans 'Look for something' %}" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
        </form>
    </div>
</nav>

wikibsteros/templates/nav.html
{% load i18n %}
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="">{% trans "Home" %}</a>
      <a class="navbar-brand js-scroll-trigger" href="{% url 'wikibsteros:universe' %}">{% trans "Universe" %}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#signup">Rytsas {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'account:profile' %}">{% trans "Profile" %}</a>
          </li>
          <a class="nav-link js-scroll-trigger" href="{% url 'wikibsteros:logout' %}">{% trans "Logging off" %}<img src=""
              height="30px"></a>
        </ul>
      </div>
      {% else %}
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#signup">{% trans "Authentication" %}</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
  </nav>

wikibsteros/templates/universe.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}
{% load humanize %}
{% include 'head.html' %}
{% include 'little-nav.html' %}
<section class="bg-light">
    <div style="padding-top:50px"></div>
    <div class="container text-center">
        <h1>{% trans "TOP 3 characters" %} ⭐</h1>
        <hr class="my-4">
        <div class="card-deck">
            {% for c in characters %}
            <div class="card">
                <img src="{{ c.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'wikibsteros:character' c.id  %}">
                        <h5 class="card-title">{{ c.name }}</h5>
                    </a>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <p class="card-text"><small class="text-muted">⭐ {{ c.note|floatformat:2 }}</small></p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div style="padding-top:50px"></div>
        <h1>{% trans "TOP 3 cities" %} ⭐</h1>
        <hr class="my-4">
        <div class="card-deck">
            {% for c in cities %}
            <div class="card">
                <img src="{% static 'wikibsteros/img/' %}{{ c.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'wikibsteros:city' c.id  %}">
                        <h5 class="card-title">{{ c.name }}</h5>
                    </a>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <p class="card-text"><small class="text-muted">🔺{{ c.population|intcomma }}
                            {% trans "inhabitants" %}</small></p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div style="padding-top:50px"></div>
        <h1>{% trans "TOP 3 houses" %} ⭐</h1>
        <hr class="my-4">
        <div class="card-deck">
            {% for i in "123" %}
            <div class="card">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to
                        additional content. This content is a little bit longer.</p>
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div style="padding-top:50px"></div>
    </div>
</section>
{% include 'footer.html' %}